#!/usr/bin/env bash

# Bash Strict Mode
set -euo pipefail

# ouput function
output () {
	>&2 echo "\033[36m$1\033[0m"
}

outputError () {
	>&2 echo "\033[41m$1\033[0m"
}

outputSuccess () {
	>&2 echo "\033[32m$1\033[0m"
}

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
FILE_COUNT=0
ERROR_COUNT=0

output "Shuffling your tiles..."

for file in $(git diff-index --diff-filter=d --cached --name-only HEAD)
do
    # we only want to lint the staged changes, not any un-staged changes
	npx prettier $file --write --ignore-unknown
	npx eslint --fix-dry-run --no-warn-ignored "$file"
	npx tsc --noEmit
    if [ $? -ne 0 ]; then
        ERROR_COUNT=$(($ERROR_COUNT+1))
    fi

	echo "$file" | git add $file
	FILE_COUNT=$(($FILE_COUNT+1))
done

if [[ "$FILE_COUNT" == 0 ]]; then
	output "Formatting skipped"
elif [[ "$ERROR_COUNT" == 0 ]]; then
	outputSuccess "$FILE_COUNT file(s) Formatted"
else
    outputError "$ERROR_COUNT files has Errors"
    exit 1
fi

outputSuccess "🀄️ Mahjong!"
